title = "Bartholomew Documentation"
base_url = "http://localhost:3000"
about = "The Micro-CMS for WebAssembly and Spin"

[extra]
copyright = "Fermyon"
github = "https://github.com/fermyon/bartholomew"
twitter = "https://twitter.com/fermyontech"
ga_measurement_id = "G-T8CY3FLH9M"

date_style = "%B %e, %Y"
