name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: set the release version (tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: rustup target add wasm32-wasi

      - name: Build WASM
        run: make build

      - name: Build bart
        run: make bart

      - name: generate checksums
        run: |
          sha256sum target/wasm32-wasi/release/bartholomew.wasm > checksums-${{ env.RELEASE_VERSION }}.txt
          sha256sum target/release/bart >> checksums-${{ env.RELEASE_VERSION }}.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/wasm32-wasi/release/bartholomew.wasm
            target/release/bart
            checksums-${{ env.RELEASE_VERSION }}.txt
