[package]
name = "spin-templates"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.1"
console = "0.15"
dialoguer = "0.10"
dirs = "3.0"
env_logger = "0.9"
fs_extra = "1.2"
futures = "0.3"
heck = "0.4"
indexmap = { version = "1", features = ["serde"] }
itertools = "0.10.3"
lazy_static = "1.4.0"
liquid = "0.23"
liquid-core = "0.23"
liquid-derive = "0.23"
liquid-lib = "0.23"
log = { version = "0.4", default-features = false }
path-absolutize = "3.0.13"
pathdiff = "0.2.1"
regex = "1.5.4"
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
sha2 = "0.10.1"
symlink = "0.1"
tempfile = "3.3.0"
tokio = { version = "1.10", features = [ "fs", "process", "rt", "macros" ] }
toml = "0.5"
url = "2.2.2"
walkdir = "2"
wasmtime = { version = "0.39.1", features = [ "async" ] }
wasmtime-wasi = "0.39.1"

[dependencies.wit-bindgen-wasmtime]
git = "https://github.com/bytecodealliance/wit-bindgen"
rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba"
features = ["async"]
